// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: api.proto

package grpcats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cats_GetCat_FullMethodName = "/grpcats.Cats/GetCat"
)

// CatsClient is the client API for Cats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatsClient interface {
	GetCat(ctx context.Context, in *CatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CatResponse], error)
}

type catsClient struct {
	cc grpc.ClientConnInterface
}

func NewCatsClient(cc grpc.ClientConnInterface) CatsClient {
	return &catsClient{cc}
}

func (c *catsClient) GetCat(ctx context.Context, in *CatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cats_ServiceDesc.Streams[0], Cats_GetCat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CatRequest, CatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cats_GetCatClient = grpc.ServerStreamingClient[CatResponse]

// CatsServer is the server API for Cats service.
// All implementations must embed UnimplementedCatsServer
// for forward compatibility.
type CatsServer interface {
	GetCat(*CatRequest, grpc.ServerStreamingServer[CatResponse]) error
	mustEmbedUnimplementedCatsServer()
}

// UnimplementedCatsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatsServer struct{}

func (UnimplementedCatsServer) GetCat(*CatRequest, grpc.ServerStreamingServer[CatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetCat not implemented")
}
func (UnimplementedCatsServer) mustEmbedUnimplementedCatsServer() {}
func (UnimplementedCatsServer) testEmbeddedByValue()              {}

// UnsafeCatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatsServer will
// result in compilation errors.
type UnsafeCatsServer interface {
	mustEmbedUnimplementedCatsServer()
}

func RegisterCatsServer(s grpc.ServiceRegistrar, srv CatsServer) {
	// If the following call pancis, it indicates UnimplementedCatsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cats_ServiceDesc, srv)
}

func _Cats_GetCat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatsServer).GetCat(m, &grpc.GenericServerStream[CatRequest, CatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cats_GetCatServer = grpc.ServerStreamingServer[CatResponse]

// Cats_ServiceDesc is the grpc.ServiceDesc for Cats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcats.Cats",
	HandlerType: (*CatsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCat",
			Handler:       _Cats_GetCat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
